### ISSUE TITLE
GitHub repository name seems strange

### ISSUE THREAD

**Issue by NozomiIto** [KazuCocoa/appium-source-viewer#3]
This repository name is `appium-error-screen-source`, but actual app name is `SourceViewer`. I think it is inconsistent and appium-error-screen-source is not appropriate name for this Appium screen shot and source viewer.

**Comment by KazuCocoa** [comment]
It's correct.
I'll rename this repository to `appium-source-viewer`. Make sense the name than original one? :)

**Comment by KazuCocoa** [comment]
(I'll work after my work.)

**Comment by NozomiIto** [comment]
Sounds better than the original one!

**Comment by KazuCocoa** [comment]
https://github.com/KazuCocoa/appium-source-viewer
