### ISSUE TITLE
Automatically load XML source tree

### ISSUE THREAD

**Issue by NozomiIto** [KazuCocoa/appium-source-viewer#4]
An image is automatically loaded to the viewer just by specifying the image file path, but on the other hand a source tree is not loaded automatically even after specifying the source path. I always must click Refresh button to load the source tree.
I'm glad if source tree is automatically loaded.

**Comment by KazuCocoa** [comment]
Simply, I add reload after selecting paths for the screenshot and the source. It's enough so far, I guess.

https://github.com/KazuCocoa/appium-source-viewer/releases/tag/v0.0.2
@NozomiIto

**Comment by NozomiIto** [comment]
Thank you!
