### ISSUE TITLE
Element properties viewer

### ISSUE THREAD

**Issue by NozomiIto** [KazuCocoa/appium-source-viewer#5]
I know Appium Desktop can display various element information such as bounds, clickable, checked, and so on. But this viewer does not support such features. I'd like to see such property information with this viewer.

**Comment by KazuCocoa** [comment]
yeah, I dropped the viewer because of keeping minimal implementation.
I plan to work this issue as the future task.

**Comment by KazuCocoa** [comment]
https://github.com/KazuCocoa/appium-source-viewer/releases/tag/v0.0.4
